============================= test session starts ==============================
platform linux -- Python 3.9.16, pytest-7.2.1, pluggy-1.0.0
rootdir: /workspace
collected 16 items
tests/test_a_environment.py ..                                           [ 12%]
tests/test_a_setup.py .                                                  [ 18%]
tests/test_distances.py ...                                              [ 37%]
tests/test_generate_regression_data.py ..                                [ 50%]
tests/test_knn.py .F...                                                  [ 81%]
tests/test_metrics.py .                                                  [ 87%]
tests/test_polynomial_regression.py ..                                   [100%]
=================================== FAILURES ===================================
_______________________________ test_knn_k_is_1 ________________________________
>                   accuracy = run(datasets[key], fraction,
                                   n_neighbors=1,
                                   distance_measure=distance_measure,
                                   aggregator="mode")
tests/test_knn.py:67:
>           raise ValueError(
                "Classification metrics can't handle a mix of {0} and {1} targets".format(
                    type_true, type_pred
                )
            )
E           ValueError: Classification metrics can't handle a mix of binary and continuous targets
/usr/local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:95: ValueError
=============================== warnings summary ===============================
tests/test_knn.py::test_knn_k_is_1
tests/test_knn.py::test_knn_k_is_1
tests/test_knn.py::test_knn_k_is_1
  /workspace/src/distances.py:67: RuntimeWarning: invalid value encountered in scalar divide
    cdist[i,j] = 1-(np.sum(np.matmul(X[i,:],Y[j,:]))/(np.sqrt(np.sum(X[i,:]**2))*np.sqrt(np.sum(Y[j,:]**2))))
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED tests/test_knn.py::test_knn_k_is_1 - ValueError: Classification metric...
================== 1 failed, 15 passed, 3 warnings in 31.44s ===================